[package]
name = "p-8"
version = "1.31.0-dev"
authors = ["Justin Karneges <justin@karneges.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
clap = { version = "2.33", features = ["wrap_help"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zmq = "0.9"
