[package]
name = "condure"
version = "1.2.0"
authors = ["Justin Karneges <justin@fanout.io>"]
license = "Apache-2.0"
description = "HTTP/WebSocket connection manager"
repository = "https://github.com/fanout/condure"
readme = "README.md"
edition = "2018"
autobins = false

[[bin]]
name = "condure"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
arrayvec = "0.5"
base64 = "0.12"
clap = { version = "2.33", features = ["wrap_help"] }
httparse = "1.3"
iovec = "0.1"
log = "0.4"
mio = { version = "0.7", features = ["os-poll", "os-ext", "net"] }
openssl = "0.10"
sha1 = "0.6"
signal-hook = "0.3"
slab = "0.4"
time = "0.1"
zmq = "0.9"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "server"
harness = false

[package.metadata.deb]
extended-description = """\
Condure is a service that manages network connections on behalf of server
applications, in order to allow controlling the connections from multiple
processes. Applications communicate with Condure over ZeroMQ.

Condure can only manage connections for protocols it knows about. Currently
this is HTTP/1 and WebSockets.

The project was inspired by Mongrel2.
"""
separate-debug-symbols = true
build-depends = "pkg-config, libzmq3-dev"
