[package]
name = "rrx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
clap = { version = "3.0.7", features = ["derive"] }
itertools = "0.10.3"
colored = "2.0.0"
