[package]
name = "p-8"
version = "1.32.0-dev"
authors = ["Justin Karneges <justin@karneges.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
base64 = "0.12"
clap = { version = "2.33", features = ["wrap_help"] }
log = "0.4"
mio = { version = "0.7", features = ["os-poll", "os-ext", "net"] }
rustls = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
webpki = "0.21"
webpki-roots = "0.21"
zmq = "0.9"
