#!/usr/bin/env python

import sys
import os
from setproctitle import setproctitle
from runner import runner

setproctitle("p-8")

exedir = os.path.dirname(os.path.realpath(__file__))

config_file_list = list()
verbose = False

for arg in sys.argv:
	if arg.startswith("--config="):
		config_file_list.append(arg[9:])
		break
	elif arg == "--verbose":
		verbose = True

# config file in same dir as executable
config_file_list.append(os.path.join(exedir, "p-8.conf"))

# config file in /etc
config_file_list.append("/etc/p-8/p-8.conf")

config_file = None
for f in config_file_list:
	if os.path.isfile(f):
		config_file = f
		break

if not config_file:
	print "Error: no configuration file found. Tried %s" % ", ".join(config_file_list)
	sys.exit(1)

runner.run(exedir, config_file, verbose)
