[package]
name = "viable_cli"
description = "A CLI wrapping the Viable language compiler"
homepage = "https://github.com/yoav-lavi/viable"
repository = "https://github.com/yoav-lavi/viable"
readme = "README.md"
version = "0.14.3"
edition = "2021"
rust-version = "1.58.0"
license = "MIT"
keywords = ["viable", "viablelang", "language", "cli"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
colored = "2.0.0"
thiserror = "1.0"
anyhow = "1.0"
viable_compiler = { version = "0.14.0", path = "../viable_compiler" }
atty = "0.2"
exitcode = "1.1.2"

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
unindent = "0.1.8"
tempfile = "3.3.0"

[[bin]]
name = "viable"
path = "./src/main.rs"
