[package]
name = "viable_compiler"
description = "The Viable language compiler"
homepage = "https://github.com/yoav-lavi/viable"
repository = "https://github.com/yoav-lavi/viable"
readme = "README.md"
version = "0.16.0"
edition = "2021"
rust-version = "1.58.0"
license = "MIT"
keywords = ["viable", "viablelang", "language", "compiler"]
categories = ["compilers"]

[features]
fuzzer = ["arbitrary"]

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
once_cell = "1.10.0"
arbitrary = { version = "1", features = ["derive"], optional = true }
thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "benchmark"
harness = false
