[package]
name = "viable_wasm"
version = "0.1.1"
edition = "2021"
rust-version = "1.58.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
viable_compiler = { version = "0.1.1", path = "../viable_compiler" }
wasm-bindgen = "0.2.79"
