[package]
name = "viable_wasm"
version = "0.5.0"
edition = "2021"
rust-version = "1.58.0"
description = "WASM bindings for the Viable language compiler"
license = "MIT"
repository = "https://github.com/yoav-lavi/viable"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
viable_compiler = { version = "0.5.0", path = "../viable_compiler" }
